replicaCount: 1

image:
  repository: ghcr.io/whospiko/patient-service
  tag: "e5e74dffe5baa9e7741f6ccd5e46a4ae66be8c40"
  pullPolicy: IfNotPresent

imagePullSecrets: []

containerPort: 3002

service:
  type: ClusterIP
  port: 3002

config:
  NODE_ENV: development
  PORT: "3002"

migration:
  enabled: false

existingSecret: patient-service-secret

health:
  enabled: false

  readinessPath: /api/health
  livenessPath: /api/health

resources:

  requests:
    cpu: 100m
    memory: 128Mi

  limits:
    cpu: 500m
    memory: 512Mi

ingress:
  enabled: false

autoscaling:
  enabled: false