replicaCount: 1

image:
  repository: ghcr.io/whospiko/patient-service
  tag: sha-initial
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-pull

containerPort: 3002

service:
  type: ClusterIP
  port: 3002

config:
  NODE_ENV: development
  PORT: "3002"

  # PATIENT_SERVICE_URL: http://patient-service:3002

#existingSecret: booking-service-secret

health:
  enabled: true
  path: /api/health

resources:
  requests:
    cpu: 100m
    memory: 128Mi

  limits:
    cpu: 500m
    memory: 512Mi