replicaCount: 1

image:
  repository: ghcr.io/whospiko/patient-service
  tag: "c16da3bf0531cb205844b5da8b84d3df89a0c6e2"
  pullPolicy: IfNotPresent

imagePullSecrets:  []

containerPort: 3002

service:
  type: ClusterIP
  port: 3002

config:
  NODE_ENV: production
  PORT: "3002"

existingSecret: patient-service-secret

health:
  enabled: false

  readinessPath: /api/health
  livenessPath: /api/health

resources:

  requests:
    cpu: 100m
    memory: 128Mi

  limits:
    cpu: 500m
    memory: 512Mi

ingress:
  enabled: false

autoscaling:

  enabled: true

  minReplicas: 2
  maxReplicas: 5

  targetCPUUtilizationPercentage: 70

migration:
  enabled: false