replicaCount: 1

image:
  repository: ghcr.io/whospiko/patient-service
  tag: "sha-f51f2ba5d709186b08ba0266d4c2642cba31135a"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-pull

containerPort: 3002

service:
  type: ClusterIP
  port: 3002

config:
  NODE_ENV: production
  PORT: "3002"

existingSecret: patient-service-secret

health:
  enabled: true

  readinessPath: /api/health
  livenessPath: /api/health

resources:

  requests:
    cpu: 100m
    memory: 128Mi

  limits:
    cpu: 500m
    memory: 512Mi

ingress:
  enabled: false

autoscaling:

  enabled: true

  minReplicas: 2
  maxReplicas: 5

  targetCPUUtilizationPercentage: 70