apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Release.Name }}

  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}

  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}

    spec:

      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        - name: {{ .Release.Name }}

          image: "{{ .Values.image.repository }}:{{ required "image.tag is required" .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}

          envFrom:
            {{- if .Values.config }}
            - configMapRef:
                name: {{ .Release.Name }}
            {{- end }}

            {{- if .Values.existingSecret }}
            - secretRef:
                name: {{ .Values.existingSecret }}
            {{- end }}

          {{- if .Values.health.enabled }}

          readinessProbe:
            httpGet:
              path: {{ .Values.health.path }}
              port: http

            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: {{ .Values.health.path }}
              port: http

            initialDelaySeconds: 15
            periodSeconds: 20

          {{- end }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}