{{- if .Values.migration.enabled }}
{{- $appName := required "appName is required for migration job" .Release.Name }}
{{- $secretName := required "existingSecret is required for migration job" .Values.existingSecret }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "%s-migrate-%s" $appName (.Values.image.tag | trunc 8) | trunc 63 | trimSuffix "-" }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded,HookFailed
spec:
  backoffLimit: 2
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          command:
            - bun
            - migrate.js
          env:
            - name: NODE_ENV
              value: {{ .Values.config.NODE_ENV | quote }}

            - name: TYPEORM_MIGRATION_MODE
              value: "bundle"

          envFrom:
            - secretRef:
                name: {{ $secretName | quote }}
{{- end }}