{{- if .Values.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.appName }}-migrate-{{ .Values.image.tag | trunc 8 }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
spec:
  backoffLimit: 2
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          command:
            - bun
            - migrate.js
          env:
            - name: NODE_ENV
              value: {{ .Values.config.NODE_ENV | quote }}

            - name: TYPEORM_MIGRATION_MODE
              value: "bundle"
          envFrom:

            {{- if .Values.existingSecret }}
              - secretRef:
                  name: {{ .Values.existingSecret }}
            {{- end }}

{{- end }}