apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet

metadata:
  name: clinic-mgnt-dev
  namespace: argocd

spec:
  goTemplate: true

  goTemplateOptions:
    - missingkey=error

  generators:
    - git:
        repoURL: https://github.com/whospiko/clinic-gitops
        revision: main

        directories:
          - path: environments/dev/clinic-mgnt

  template:
    metadata:
      name: 'dev-{{ .path.basename }}'

    spec:
      project: clinic

      source:
        repoURL: https://github.com/whospiko/clinic-gitops
        targetRevision: main

        path: charts/clinic-mgnt

        helm:
          releaseName: '{{ .path.basename }}'

          valueFiles:
            - '../../{{ .path.path }}/values.yaml'

      destination:
        server: https://kubernetes.default.svc
        namespace: clinic-frontend-dev

      syncPolicy:
        automated:
          prune: true
          selfHeal: true

        syncOptions:
          - CreateNamespace=true