apiVersion: argoproj.io/v1alpha1
kind: AppProject

metadata:
  name: clinic
  namespace: argocd

spec:
  description: Clinic Platform GitOps Project

  sourceRepos:
    - https://github.com/whospiko/clinic-gitops

  destinations:
    - namespace: clinic-dev
      server: https://kubernetes.default.svc

    - namespace: clinic-frontend-dev
      server: https://kubernetes.default.svc

    - namespace: clinic-prod
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"