replicaCount: 1

image:
  repository: ghcr.io/whospiko/booking-service
  tag: "sha-bf3da0986bd60a348016a9b5cd135bc46678def8"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-pull

containerPort: 3001

service:
  type: ClusterIP
  port: 3001

config:
  NODE_ENV: development
  PORT: "3001"

  PATIENT_SERVICE_URL: http://patient-service:3002

existingSecret: booking-service-secret

health:
  enabled: true

  readinessPath: /api/health
  livenessPath: /api/health

resources:

  requests:
    cpu: 100m
    memory: 128Mi

  limits:
    cpu: 500m
    memory: 512Mi

ingress:
  enabled: false

autoscaling:
  enabled: false